# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 09:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', django.contrib.postgres.fields.ranges.DateTimeRangeField(db_index=True)),
                ('list_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'get_latest_by': 'card_action__date',
            },
        ),
        migrations.AlterModelOptions(
            name='cardaction',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='cardstate',
            name='card_action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='charting.CardAction'),
        ),
        migrations.AddField(
            model_name='cardstate',
            name='next_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_state', to='charting.CardState'),
        ),
    ]
