# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charting', '0003_auto_20160719_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='trello_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
