# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charting', '0004_auto_20160719_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardaction',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
