# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charting', '0005_auto_20160720_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardstate',
            name='card_action',
        ),
        migrations.RemoveField(
            model_name='cardstate',
            name='next_state',
        ),
        migrations.DeleteModel(
            name='CardState',
        ),
    ]
