# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charting', '0006_auto_20160720_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardaction',
            name='list',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_actions', to='charting.List'),
        ),
    ]
