# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charting', '0007_auto_20160720_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='trello_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='list',
            name='trello_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
